=== yorch4/TrabajosPRG/kk/src/LSMGI/Examen.dtd
<!ELEMENT TeatrosLucena (teatro*)>
<!ENTITY tamaño "500m2">
<!ENTITY % atributoNumero "numero CDATA #IMPLIED">
<!ELEMENT teatro (personas ,tamaño?, actor+, (obraDia1* | obraDia2*), amigos?)>
<!ATTLIST teatro nombre CDATA #REQUIRED>
<!ELEMENT personas EMPTY>
<!ATTLIST personas %atributoNumero;>
<!ELEMENT tamaño (#PCDATA | largo)*>
<!ELEMENT largo (#PCDATA)>
<!ELEMENT actor EMPTY>
<!ELEMENT obraDia1 EMPTY>
<!ATTLIST actor nombre ID #IMPLIED>
<!ATTLIST obraDia1 nombre CDATA #FIXED "El Mago de Oz">
<!ATTLIST obraDia1 protagonistas IDREFS #IMPLIED>
<!ATTLIST obraDia1 estrella IDREF #IMPLIED>
<!ELEMENT obraDia2 EMPTY>
<!ATTLIST obraDia2 nombre (CaperucitaRosa | ReyLeon) #IMPLIED>
<!ELEMENT amigos EMPTY>
<!ATTLIST amigos %atributoNumero;>

=== yorch4/TrabajosPRG/kk/src/LSMGI/Examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TeatrosLucena SYSTEM "Examen.dtd">

<TeatrosLucena>
	<teatro nombre="Teatrín">
		<personas numero="460"></personas>
		<tamaño> &tamaño; </tamaño>
		<actor nombre="Juan"/>
		<actor nombre="Maria"/>
		<obraDia1 nombre="El Mago de Oz"></obraDia1>
		<obraDia1 protagonistas="Juan Maria"></obraDia1>
		<obraDia1 estrella="Juan"></obraDia1>
	</teatro>
	<teatro nombre="Espectáculo">
		<personas></personas>
		<tamaño></tamaño>
		<actor nombre="Pedro"></actor>
		<actor nombre="Elena"></actor>
		<obraDia2 nombre="CaperucitaRosa"></obraDia2>
		<amigos numero="20"></amigos>
	</teatro>
</TeatrosLucena>
