=== yorch4/TrabajosPRG/kk/bin/LSMGI/CorreosElectronicos.dtd
<!ELEMENT emails (email*)>
<!ELEMENT email (para*, cc*, cco*, asunto, texto, adjunto)*>
<!ELEMENT para (#PCDATA)>
<!ELEMENT cc (#PCDATA)>
<!ELEMENT cco (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT texto (#PCDATA)>
<!ELEMENT adjunto (nombre, mime-type, longitud)*>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT mime-type (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>

=== yorch4/TrabajosPRG/kk/src/kk/CorreosElectronicos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE emails SYSTEM "CorreosElectronicos.dtd">
<emails>
	<email>
		<para></para>
		<cc></cc>
		<cco></cco>
		<asunto></asunto>
		<texto></texto>
		<adjunto>
			<nombre></nombre>
			<mime-type></mime-type>
			<longitud></longitud>
		</adjunto>
	</email>
</emails>
